/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.DsClient;

import main.java.com.DsClient.overlay.*;
import main.java.com.DsClient.udp.Udpclient;
import main.java.com.DsClient.udp.Udpserver;
public class Main {
 
    public static void main(String[] args) {
        
    }
}