/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.DsClient;

import main.java.com.DsClient.overlay.*;
public class Main {
 
    public static void main(String[] args) {
        Overlay.main(args);
    }
}
