/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.DsClient;

import com.DsClient.Overlay;
public class Main {
 
    public static void main(String[] args) {
        Overlay.main();
    }
}
